# Generated by Django 3.0.6 on 2020-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucreator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='menu',
            field=models.ManyToManyField(to='menucreator.Menu'),
        ),
    ]
