# Generated by Django 3.0.6 on 2020-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucreator', '0003_menucategory_max_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='max_quantity',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='max_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
