# Generated by Django 3.0.6 on 2020-05-24 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menucreator', '0004_auto_20200524_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
